### ISSUE TITLE
Suggestion to remove this repo..

### ISSUE THREAD

**Issue by pgmoftexas** [ianpgmoftexas/ianpgmoftexas.github.io#1]
Suggestion to remove this repo.. visceral betrayal.

**Comment by ianpgmoftexas** [comment]
And how exactly is this considered a "visceral betrayal"?

**Comment by pgmoftexas** [comment]
![puppies-cover-1280x720](https://user-images.githubusercontent.com/44447923/96478227-0d272780-11fd-11eb-83ea-726aaccfbe0c.jpg)

**Comment by ianpgmoftexas** [comment]
I'm sorry to hear you're not a fan of puppies. Closing this ticket as this is simply a stock image for testing the WebMention API with h-card semantics.
